### ISSUE TITLE
As I know, the malignant of each patient in LIDC data is marked by 1 to 4 doctors. But in your method, it seems that each patient has only one malignant grade. How do you deal with it?

### ISSUE THREAD

**Issue by CreepingBird** [jcausey-astate/NoduleX_code#2]
As I know, the malignant of each patient in LIDC data is marked by 1 to 4 doctors. But in your method, it seems that each patient has only one malignant grade. How do you deal with it?

**Comment by jcausey-astate** [comment]
We created a consensus score for each nodule by averaging the ratings assigned by the LIDC radiologists.  Since different slices were sometimes rated by different numbers of radiologists, we sum the ratings on a per-slice level, divide by the total number of ratings the nodule received as a whole, and round to the nearest integer.
